FROM python:3.9.16

RUN pip install numpy==1.24.3 \
    pandas==1.5.3 \
    matplotlib==3.7.1 \
    opencv-python==4.7.0.72 \
    requests==2.30.0

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y libgl1-mesa-dev

